name: Quarto Render and Publish

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render HTML to docs/
        run: quarto render --output-dir docs

      - name: Commit rendered docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/*
          git commit -m "Render Quarto site to docs"
          git push
